name: simpleQRGenerator

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2

    # Configurar Docker Buildx y login a Docker Hub
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_SECRET }}

    # Construir y empujar la imagen del backend
    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_LOGIN }}/qr-backend:latest